### ISSUE TITLE
Tutorial's mistakes

### ISSUE THREAD

**Issue by 1xtr** [microsoftgraph/msgraph-training-javascriptspa#31]
### Where did you get the code?

- [ ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

In [Russian tutorial step 1](https://docs.microsoft.com/ru-ru/graph/tutorials/javascript?context=outlook%2Fcontext&tutorial-step=1) two mistakes in file name:

> 3. Создайте новый файл **с**auth.js и добавьте следующий код.

> 4. Создайте новый файл **с**ui.js и добавьте следующий код.

extra C at the beginning of the filename

Next:

On [registration app step](https://docs.microsoft.com/ru-ru/graph/tutorials/javascript?context=outlook%2Fcontext&tutorial-step=2) need next step with add permissions for  Calendars.ReadWrite and MailboxSettings.Read
because by default after registration we have only User.Read permission in new app

in config.js 
```
const msalRequest = {
  scopes: [
    'user.read', // set by default
    'mailboxsettings.read', // not set by default and app crashed with error
    'calendars.readwrite' // not set by default and app crashed with error
  ]
}
```

sorry for this, not complete, typing errors

**Comment by jasonjoh** [comment]
I'll report the Russian error to our localization team, thanks for reporting!

On the app registration - you do not need to configure the permissions ahead of time. The app uses dynamic consent to request those permissions, see https://docs.microsoft.com/azure/active-directory/develop/v2-permissions-and-consent#incremental-and-dynamic-user-consent. The app should not be crashing due to these not being configured, there must be something else happening.
